# Generated by Django 4.0.5 on 2022-06-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_alter_event_options_alter_subeventtype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='totalTime',
            field=models.TimeField(blank=True),
        ),
    ]
